# Generated by Django 5.2.8 on 2025-11-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('icon_color', models.CharField(default='#ffffff', help_text='Hex боја за кружето (пример: #f7931a)', max_length=20)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
    ]
