# Generated by Django 5.2.8 on 2025-11-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocoin',
            options={'managed': False},
        ),
    ]
