# Generated by Django 5.2.8 on 2025-11-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cryptocoin_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cryptocoin',
            table='crypto_ohlcv',
        ),
    ]
